### ISSUE TITLE
WebInterface^

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#101]
root@orangepi3:~/botamusique# python3 mumbleBot.py
[Mar 14 11:33:58 INFO MainThread] bot: botamusique version 6.0, starting...
[Mar 14 11:33:58 INFO MainThread] Starting web interface on 192.168.10.10:8181
[Mar 14 11:33:58 INFO MainThread] library: rebuild directory cache
 * Serving Flask app "interface" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://192.168.10.10:8181/ (Press CTRL+C to quit)
[Mar 14 11:36:21 INFO MainThread] bot: load playlist from previous session
[2020-03-14 11:36:21,522] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/botamusique/interface.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/root/botamusique/interface.py", line 150, in index
    path_tags_lookup = build_path_tags_lookup()
  File "/root/botamusique/interface.py", line 129, in build_path_tags_lookup
    id_tags_lookup = var.music_db.query_tags_by_ids(ids)
  File "/root/botamusique/database.py", line 265, in query_tags_by_ids
    results = cursor.execute("SELECT id, tags FROM music "
sqlite3.OperationalError: Expression tree is too large (maximum depth 1000)
192.168.10.1 - - [14/Mar/2020 11:36:21] "GET / HTTP/1.1" 500 -

**Comment by TerryGeng** [comment]
Duplicated
