### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#115]
![image](https://user-images.githubusercontent.com/51275636/77824360-38d4aa00-7113-11ea-9490-6c0f8839cdff.png)

root@orangepi3:~/botamusique# python3 mumbleBot.py
[Mar 28 13:37:54 INFO MainThread] bot: botamusique version 6.0, starting...
[Mar 28 13:37:54 INFO MainThread] Starting web interface on 192.168.10.10:8181
[Mar 28 13:37:54 INFO MainThread] library: rebuild directory cache
 * Serving Flask app "interface" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://192.168.10.10:8181/ (Press CTRL+C to quit)
[Mar 28 13:41:39 INFO MainThread] bot: load playlist from previous session
[2020-03-28 13:41:39,675] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/botamusique/interface.py", line 101, in decorated
    return f(*args, **kwargs)
  File "/root/botamusique/interface.py", line 157, in index
    dirs=get_all_dirs(),
  File "/root/botamusique/interface.py", line 138, in get_all_dirs
    pos = path.find("/", pos+1)
AttributeError: 'NoneType' object has no attribute 'find'
195.93.165.207 - - [28/Mar/2020 13:41:39] "GET / HTTP/1.1" 500 -

What I tried:
- restart the bot
- restart mumble
- restart orangepi
- disable music folder(1500+ songs)
Not work(

**Comment by TerryGeng** [comment]
Which version you are using? Is it the newest one from the master branch?

**Comment by LDelOff** [comment]
I update bot 40 minetes ago

**Comment by LDelOff** [comment]
I noticed this malfunction 3 days ago. But there was no time to figure it out.

**Comment by TerryGeng** [comment]
I posted a hotfix in `da3f3cd42f7fc7b7706be5c245b799348d12cb6c`. Can you have a look?

**Comment by LDelOff** [comment]
Yes, everything works correctly
