### ISSUE TITLE
Error while using !search feature

### ISSUE THREAD

**Issue by riauas** [azlux/botamusique#117]
Just updated botamusique to ver 6.1, sometimes the bot suddenly killed (systemctl status said the bot service still working) and not working !search feature have this error on the log:
```
[Mar 31 04:31:46 INFO Thread-9] bot: received command se - party by SuperUser
[Mar 31 04:31:46 INFO Thread-9] bot: se matches search
[Mar 31 04:31:46 INFO Thread-9] file: music file missed for [file] iwannaparty (iwannaparty.mp3)
[Mar 31 04:31:46 ERROR Thread-9] bot: command search failed with error: Traceback (most recent call last):
  File "/home/andry_a3/Downloads/botamusique/mumbleBot.py", line 295, in message_received
    self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, parameter)
  File "/home/andry_a3/Downloads/botamusique/command.py", line 1024, in cmd_search_library
    items = dicts_to_items(bot, music_dicts)
  File "/home/andry_a3/Downloads/botamusique/media/item.py", line 29, in dicts_to_items
    items.append(item_loaders[type](bot, music_dict))
  File "/home/andry_a3/Downloads/botamusique/media/file.py", line 30, in file_item_loader
    return FileItem(bot, "", _dict)
  File "/home/andry_a3/Downloads/botamusique/media/file.py", line 59, in __init__
    if not self.validate():
  File "/home/andry_a3/Downloads/botamusique/media/file.py", line 74, in validate
    self.send_client_message(constants.strings('file_missed', file=self.path))
  File "/home/andry_a3/Downloads/botamusique/media/item.py", line 109, in send_client_message
    self.bot.send_msg(msg)
TypeError: send_msg() missing 1 required positional argument: 'text'
```

I remembered not have these problems on ver. 6.0. Any clue to solve it?
Thank you

**Comment by TerryGeng** [comment]
Sorry my fault.

It's fixed in the master branch, but it may take some days for @azlux's auto-update to be ready.

As a workaround, you can drop the database by `!dropdatabase` and let the bot rebuild the cache again, but you will lose all the tags if you do so.

**Comment by riauas** [comment]
Thank you i'll try with !dropdatabase's way.

**Comment by TerryGeng** [comment]
Hi, @azlux and I have just posted a new release that fixed this issue. Please remember to auto-update. Feel free to let us know if you discover more bugs :).
