### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Mati20187** [azlux/botamusique#119]
**Describe the bug**
When trying to launch the bot with the command `venv/bin/python mumbleBot.py --config configuration.ini` I get this error:
```
Traceback (most recent call last):
  File "mumbleBot.py", line 20, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```
**Affected version**
Latest stable (6.1.1)

I've tried reinstalling the bot and installed the _packaging_ module with `pip install packaging` but the error still occurs.

**Comment by azlux** [comment]
It's because you should do `venv/bin/pip install --upgrade -r requirements.txt`

**Comment by Mati20187** [comment]
I've tried it before but pillow doesn't want to install. Output:
```
$ venv/bin/pip install --upgrade -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple 
Requirement already up-to-date: opuslib==2.0.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.0.0) 
Requirement already up-to-date: protobuf==3.4.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (3.4.0) 
Requirement already up-to-date: flask in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.1.1) 
Requirement already up-to-date: youtube-dl in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2020.3.24) 
Requirement already up-to-date: python-magic in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.4.15) 
Collecting Pillow 
  Using cached Pillow-7.1.0.tar.gz (38.9 MB) 
Requirement already up-to-date: mutagen in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.44.0) 
Requirement already up-to-date: requests in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.23.0) 
Requirement already up-to-date: packaging in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (20.3) 
Requirement already satisfied, skipping upgrade: setuptools in ./venv/lib/python3.7/site-packages (from protobuf==3.4.0->-r requirements.txt (line 2)) (40.8.0) 
Requirement already satisfied, skipping upgrade: six>=1.9 in ./venv/lib/python3.7/site-packages (from protobuf==3.4.0->-r requirements.txt (line 2)) (1.14.0) 
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in ./venv/lib/python3.7/site-packages (from flask->-r requirements.txt (line 3)) (1.1.0) 
Requirement already satisfied, skipping upgrade: Werkzeug>=0.15 in ./venv/lib/python3.7/site-packages (from flask->-r requirements.txt (line 3)) (1.0.1) 
Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in ./venv/lib/python3.7/site-packages (from flask->-r requirements.txt (line 3)) (2.11.1) 
Requirement already satisfied, skipping upgrade: click>=5.1 in ./venv/lib/python3.7/site-packages (from flask->-r requirements.txt (line 3)) (7.1.1) 
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 8)) (3.0.4) 
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 8)) (2019.11.28) 
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 8)) (1.25.8) 
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in ./venv/lib/python3.7/site-packages (from requests->-r requirements.txt (line 8)) (2.9) 
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in ./venv/lib/python3.7/site-packages (from packaging->-r requirements.txt (line 9)) (2.4.6) 
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./venv/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->-r requirements.txt (line 3)) (1.1.1) 
Building wheels for collected packages: Pillow 
  Building wheel for Pillow (setup.py) ... error 
  ERROR: Command errored out with exit status 1: 
   command: /home/pi/botamusique/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i3li8ova 
       cwd: /tmp/pip-install-terc1f6i/Pillow/ 
  Complete output (172 lines): 
  running bdist_wheel 
  running build 
  running build_py 
  creating build 
  creating build/lib.linux-armv7l-3.7 
  creating build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL 
  running egg_info 
  writing src/Pillow.egg-info/PKG-INFO 
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt 
  writing top-level names to src/Pillow.egg-info/top_level.txt 
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt' 
  reading manifest template 'MANIFEST.in' 
  warning: no files found matching '*.c' 
  warning: no files found matching '*.h' 
  warning: no files found matching '*.sh' 
  warning: no previously-included files found matching '.appveyor.yml' 
  warning: no previously-included files found matching '.coveragerc' 
  warning: no previously-included files found matching '.editorconfig' 
  warning: no previously-included files found matching '.readthedocs.yml' 
  warning: no previously-included files found matching 'azure-pipelines.yml' 
  warning: no previously-included files found matching 'codecov.yml' 
  warning: no previously-included files matching '.git*' found anywhere in distribution 
  warning: no previously-included files matching '*.pyc' found anywhere in distribution 
  warning: no previously-included files matching '*.so' found anywhere in distribution 
  no previously-included directories found matching '.azure-pipelines' 
  no previously-included directories found matching '.ci' 
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt' 
  running build_ext 
  The headers or library files could not be found for jpeg, 
  a required dependency when compiling Pillow from source. 
  Please see the install instructions at: 
     https://pillow.readthedocs.io/en/latest/installation.html 
  Traceback (most recent call last): 
    File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 899, in <module> 
      zip_safe=not (debug_build() or PLATFORM_MINGW), 
    File "/home/pi/botamusique/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup 
      return distutils.core.setup(**attrs) 
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup 
      dist.run_commands() 
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands 
      self.run_command(cmd) 
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
      cmd_obj.run() 
    File "/home/pi/botamusique/venv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run 
      self.run_command('build') 
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command 
      self.distribution.run_command(command) 
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
      cmd_obj.run() 
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run 
      self.run_command(cmd_name) 
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command 
      self.distribution.run_command(command) 
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
      cmd_obj.run() 
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run 
      self.build_extensions() 
    File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 694, in build_extensions 
      raise RequiredDependencyException(f) 
  __main__.RequiredDependencyException: jpeg 
  During handling of the above exception, another exception occurred: 
  Traceback (most recent call last): 
    File "<string>", line 1, in <module> 
    File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 914, in <module> 
      raise RequiredDependencyException(msg) 
  __main__.RequiredDependencyException: 
  The headers or library files could not be found for jpeg, 
  a required dependency when compiling Pillow from source. 
  Please see the install instructions at: 
     https://pillow.readthedocs.io/en/latest/installation.html 
  ---------------------------------------- 
  ERROR: Failed building wheel for Pillow 
  Running setup.py clean for Pillow 
Failed to build Pillow 
Installing collected packages: Pillow 
    Running setup.py install for Pillow ... error 
    ERROR: Command errored out with exit status 1: 
     command: /home/pi/botamusique/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-erfnk6ka/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/botamusique/venv/include/site/python3.7/Pillow 
         cwd: /tmp/pip-install-terc1f6i/Pillow/ 
    Complete output (174 lines): 
    running install 
    running build 
    running build_py 
    creating build 
    creating build/lib.linux-armv7l-3.7 
    creating build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL 
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL 
    running egg_info 
    writing src/Pillow.egg-info/PKG-INFO 
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt 
    writing top-level names to src/Pillow.egg-info/top_level.txt 
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt' 
    reading manifest template 'MANIFEST.in' 
    warning: no files found matching '*.c' 
    warning: no files found matching '*.h' 
    warning: no files found matching '*.sh' 
    warning: no previously-included files found matching '.appveyor.yml' 
    warning: no previously-included files found matching '.coveragerc' 
    warning: no previously-included files found matching '.editorconfig' 
    warning: no previously-included files found matching '.readthedocs.yml' 
    warning: no previously-included files found matching 'azure-pipelines.yml' 
    warning: no previously-included files found matching 'codecov.yml' 
    warning: no previously-included files matching '.git*' found anywhere in distribution 
    warning: no previously-included files matching '*.pyc' found anywhere in distribution 
    warning: no previously-included files matching '*.so' found anywhere in distribution 
    no previously-included directories found matching '.azure-pipelines' 
    no previously-included directories found matching '.ci' 
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt' 
    running build_ext 
    The headers or library files could not be found for jpeg, 
    a required dependency when compiling Pillow from source. 
    Please see the install instructions at: 
       https://pillow.readthedocs.io/en/latest/installation.html 
    Traceback (most recent call last): 
      File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 899, in <module> 
        zip_safe=not (debug_build() or PLATFORM_MINGW), 
      File "/home/pi/botamusique/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup 
        return distutils.core.setup(**attrs) 
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup 
        dist.run_commands() 
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands 
        self.run_command(cmd) 
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
        cmd_obj.run() 
      File "/home/pi/botamusique/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run 
        return orig.install.run(self) 
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run 
        self.run_command('build') 
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command 
        self.distribution.run_command(command) 
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
        cmd_obj.run() 
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run 
        self.run_command(cmd_name) 
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command 
        self.distribution.run_command(command) 
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command 
        cmd_obj.run() 
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run 
        self.build_extensions() 
      File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 694, in build_extensions 
        raise RequiredDependencyException(f) 
    __main__.RequiredDependencyException: jpeg 
    During handling of the above exception, another exception occurred: 
    Traceback (most recent call last): 
      File "<string>", line 1, in <module> 
      File "/tmp/pip-install-terc1f6i/Pillow/setup.py", line 914, in <module> 
        raise RequiredDependencyException(msg) 
    __main__.RequiredDependencyException: 
    The headers or library files could not be found for jpeg, 
    a required dependency when compiling Pillow from source. 
    Please see the install instructions at: 
       https://pillow.readthedocs.io/en/latest/installation.html 
    ---------------------------------------- 
ERROR: Command errored out with exit status 1: /home/pi/botamusique/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-terc1f6i/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-erfnk6ka/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/botamusique/venv/include/site/python3.7/Pillow Check the logs for full command output. 
```

**Comment by Mati20187** [comment]
The problem was on my side. My system was missing _libjpeg-dev_ and _zlib1g-dev_
