### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by TylerVigario** [azlux/botamusique#144]
I figured I would bring this up here to see if I can get the bot running properly under Windows.

- Windows 10 x64
- Python 3.8 (64-bit)
- Opusfile (0.9)

I followed this [resolved issue](https://github.com/orion-labs/opuslib/issues/17) from the `opuslib` package to get Opus installed in my environment.

However, I am met with this error now.

```
Traceback (most recent call last):
  File "mumbleBot.py", line 15, in <module>
    import pymumble_py3 as pymumble
  File "C:\Python38\lib\site-packages\pymumble_py3\__init__.py", line 3, in <module>
    from .mumble import Mumble
  File "C:\Python38\lib\site-packages\pymumble_py3\mumble.py", line 12, in <module> 
    from . import users
  File "C:\Python38\lib\site-packages\pymumble_py3\users.py", line 5, in <module>   
    from . import soundqueue
  File "C:\Python38\lib\site-packages\pymumble_py3\soundqueue.py", line 6, in <module>
    import opuslib
  File "C:\Python38\lib\site-packages\opuslib\__init__.py", line 19, in <module>      
    from .classes import Encoder, Decoder  # NOQA
  File "C:\Python38\lib\site-packages\opuslib\classes.py", line 6, in <module>        
    import opuslib.api.decoder
  File "C:\Python38\lib\site-packages\opuslib\api\__init__.py", line 24, in <module>  
    libopus = ctypes.CDLL(lib_location)
  File "C:\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

Note: Yes, I messed up and installed packages site-wide.

**Comment by Lartza** [comment]
You need to compile a 64-bit opusfile or use 32-bit Python

**Comment by azlux** [comment]
@TylerVigario I've successfully setup my env with python3 64 bits.
I've write a wiki : https://github.com/azlux/botamusique/wiki/Windows-dev-environment

**Comment by TylerVigario** [comment]
@azlux Thank you very much because I struggled to find or build 64-bit Opus.

I ended up breaking down and installing Python 32-bit (leaving out of path) and created the virtual environment for botamusique with that version. Windows is a little trickier to work with venv and requires you to run `.\venv\Scripts\activate.bat` (for Command Prompt) first to work within the virtual environment.

Thanks again! Now I can switch to 64-bit Opus.

**Comment by LDelOff** [comment]
Hello, I don't understand what I'm doing wrong.
I have:
Win10 x64
Python 3.8.2 (PyCharm 2020.1.2)
I did:

> magic DLL can be obtain with pip3 install python-magic-bin

> Go on https://ci.appveyor.com/project/rillian/opus -> "ReleaseDLL; Platform: x64" -> "Artifacts" -> Download the "opus.zip", DLL is compressed inside.

> libwinpthread-1.dll and libgcc_s_seh-1.dll can be found in to the MinGW bin folder. Copy are here

I downloaded these files and moved them to C:\Windows\SysWOW64\

But when you try to run this code:

```
import pymumble_py3
server = "ldeloff.zapto.org"
nick = "Haron"
passwd = ""
mumble = pymumble_py3.Mumble(server, nick, password=passwd)
mumble.start()

```
Еrror appears:



```
"D:\Проги, проекты\Mumble\MumbleConciergeBot\venv\Scripts\python.exe" "D:/Проги, проекты/Mumble/MumbleConciergeBot/start_bot.py"
Traceback (most recent call last):
  File "D:/Проги, проекты/Mumble/MumbleConciergeBot/start_bot.py", line 1, in <module>
    import pymumble_py3
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\pymumble_py3\__init__.py", line 3, in <module>
    from .mumble import Mumble
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\pymumble_py3\mumble.py", line 12, in <module>
    from . import users
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\pymumble_py3\users.py", line 5, in <module>
    from . import soundqueue
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\pymumble_py3\soundqueue.py", line 6, in <module>
    import opuslib
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\venv\lib\site-packages\opuslib\__init__.py", line 19, in <module>
    from .classes import Encoder, Decoder  # NOQA
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\venv\lib\site-packages\opuslib\classes.py", line 6, in <module>
    import opuslib.api.decoder
  File "D:\Проги, проекты\Mumble\MumbleConciergeBot\venv\lib\site-packages\opuslib\api\__init__.py", line 21, in <module>
    raise Exception(
Exception: Could not find opus library. Make sure it is installed.

Process finished with exit code 1
```

**Comment by TylerVigario** [comment]
`SysWOW64` is actually for 32-bit and `System32` for 64-bit. 

I ended up just putting the dlls in an arbitrary folder and adding it to my path though.

**Comment by LDelOff** [comment]
It worked! Thanks! You're amazing!!!)))

**Comment by Lartza** [comment]
> 
> I ended up just putting the dlls in an arbitrary folder and adding it to my path though.

And I modified opuslib to load the DLL from an arbitary folder. In case someone ever wants to do it you edit opuslib/api/__init.py__ to say something like 
```
#lib_location = find_library('opus')

#if lib_location is None:
#    raise Exception(
#        'Could not find opus library. Make sure it is installed.')

libopus = ctypes.CDLL("C:\\Users\\Lartza\\PycharmProjects\\botamusique\\opus.dll")
```

**Comment by TylerVigario** [comment]
This time around I didn't have `libmagic` - https://github.com/nscaife/file-windows/releases/tag/20170108

**Comment by TerryGeng** [comment]
@azlux Maybe we need a special installation guide for Windows users?
