### ISSUE TITLE
No such file or directory: 'templates/index.en_US.html'

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#208]
I installed a bot today. The web interface doesn't work. Writes that the file was not found. There really isn't this file in that path. (en_US version I have in the configuration file is).

`root@ldeloff:~/botamusique# venv/bin/python mumbleBot.py
[Sep 17 15:49:43 INFO] bot: botamusique version git, starting...
[Sep 17 15:49:44 INFO] bot: load playlist from previous session
[Sep 17 15:49:44 INFO] Starting web interface on 192.168.10.10:8181
 * Serving Flask app "interface" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://192.168.10.10:8181/ (Press CTRL+C to quit)
[2020-09-17 15:51:11,429] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/botamusique/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/botamusique/interface.py", line 176, in decorated
    return f(*args, **kwargs)
  File "/root/botamusique/interface.py", line 228, in index
    return open(f"templates/index.{var.language}.html", "r").read()
FileNotFoundError: [Errno 2] No such file or directory: 'templates/index.en_US.html'
192.168.10.2 - - [17/Sep/2020 15:51:11] "GET / HTTP/1.1" 500 -`

OrangePi 3, Armbian(Ubuntu), Python 3.8.2

**Comment by azlux** [comment]
Hi,
How did you installed the bot ? look like you use the git version, without compiling the webinterface.

**Comment by LDelOff** [comment]
Yes, I use git version. Now I try curl

**Comment by LDelOff** [comment]
Curl version working correctly. I got an error in the git version when compiling the web interface.

**Comment by TerryGeng** [comment]
Hmmmm.... What error did you got? Would you like to share with us?

**Comment by LDelOff** [comment]
[botamusique git.txt](https://github.com/azlux/botamusique/files/5251304/botamusique.git.txt)

**Comment by TerryGeng** [comment]
Hi, from your log I can see you paste the last line wrong. Please run the command from our README line by line and check it is correct before running.
