### ISSUE TITLE
Encoder error in new version of pymumble

### ISSUE THREAD

**Issue by peylight** [azlux/botamusique#240]
**Describe the bug**
Seems new version pymumble have some issue with botamusique.
I'm using latest debian stable.
After update requirements i can not play music any more and i have this error:

```
[Jan 01 09:25:15 INFO] library: rebuild directory cache
[Jan 01 09:25:15 INFO] bot: botamusique version unknown, starting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 134, in run
    self.loop()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 215, in loop
    self.read_control_messages()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 289, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 431, in dispatch_control_message
    self.sound_output.set_default_codec(mess)
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/soundoutput.py", line 185, in set_default_codec
    self.create_encoder()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/soundoutput.py", line 197, in create_encoder
    raise CodecNotSupportedError('')
pymumble_py3.errors.CodecNotSupportedError: ''
```

**Affected version**
I'm using latest stable version. I mean 7.2...

**To Reproduce**
Just try to run botamusique with latest version of requirements.

**Expected behavior**
run without problem.

**Comment by TerryGeng** [comment]
Did you install opus?

**Comment by peylight** [comment]
@TerryGeng 
Of course, version 0.1.10-1
I was using it and I had no problem. until update to new version.
I check Centos, the same problem exist.

**Comment by TerryGeng** [comment]
I need more information to investigate. Would you set `mumbleConnection` to `True` in the `[debug]` section in your config file and post the output?
https://github.com/azlux/botamusique/blob/1af21a66f821c91284ccccacda861f676a2ab8db/configuration.example.ini#L160-L163

**Comment by peylight** [comment]
```
[Jan 01 10:06:59 INFO] library: rebuild directory cache
[Jan 01 10:06:59 INFO] bot: botamusique version 7.2-10-g101391f, starting...
2021-01-01 10:06:59,852-PyMumble-DEBUG-Working in STEREO mode.
2021-01-01 10:06:59,855-PyMumble-DEBUG-connecting to mumble.4gamer.ir (SocketKind.SOCK_STREAM) on port 64738.
2021-01-01 10:06:59,934-PyMumble-DEBUG-sending: version: version: 66052
release: "PyMumble 1.5"
os: "PyMumble 1.5"
os_version: "Python 3.7.3 (default, Jul 25 2020, 13:03:44) \n[GCC 8.3.0] - Linux 4.19.0-13-amd64"

2021-01-01 10:06:59,935-PyMumble-DEBUG-sending message
2021-01-01 10:06:59,936-PyMumble-DEBUG-sending: authenticate: username: "MusicBot"
password: ""
tokens: ""
opus: true

2021-01-01 10:06:59,936-PyMumble-DEBUG-sending message
2021-01-01 10:06:59,936-PyMumble-DEBUG-entering loop
2021-01-01 10:06:59,937-PyMumble-DEBUG-read control connection
2021-01-01 10:06:59,937-PyMumble-DEBUG-dispatch control message
2021-01-01 10:06:59,937-PyMumble-DEBUG-message: Version : version: 66307

2021-01-01 10:07:00,004-PyMumble-DEBUG-read control connection
2021-01-01 10:07:00,004-PyMumble-DEBUG-dispatch control message
2021-01-01 10:07:00,005-PyMumble-DEBUG-message: CryptSetup : key: "\300\310l\nU\255E|\r/L\362%%\206\361"
client_nonce: "\354\377n.\205/\235\237\361\300\204\020\270 \322\000"
server_nonce: "o\030Z\340\325C\r\200\033\357\344c\204\366\276@"

2021-01-01 10:07:00,006-PyMumble-DEBUG-sending: ping: timestamp: 1609483020
tcp_packets: 0
tcp_ping_avg: 40.0
tcp_ping_var: 0.0

2021-01-01 10:07:00,006-PyMumble-DEBUG-sending message
2021-01-01 10:07:00,006-PyMumble-DEBUG-0
2021-01-01 10:07:00,006-PyMumble-DEBUG-read control connection
2021-01-01 10:07:00,007-PyMumble-DEBUG-dispatch control message
2021-01-01 10:07:00,007-PyMumble-DEBUG-message: CodecVersion : alpha: -2147483637
beta: -2147483632
prefer_alpha: true
opus: false

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 134, in run
    self.loop()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 215, in loop
    self.read_control_messages()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 289, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/mumble.py", line 431, in dispatch_control_message
    self.sound_output.set_default_codec(mess)
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/soundoutput.py", line 185, in set_default_codec
    self.create_encoder()
  File "/home/botamusique/botamusique/venv/lib/python3.7/site-packages/pymumble_py3/soundoutput.py", line 197, in create_encoder
    raise CodecNotSupportedError('')
pymumble_py3.errors.CodecNotSupportedError: ''
```

**Comment by TerryGeng** [comment]
As shown in this part:

```
prefer_alpha: true
opus: false
```

The mumble server you are connecting to request CELT encoder.

This can be due to:
1. The mumble server you are connecting to is too old, please check the version of it.
2. One client connected to the server is an old client that doesn't support Opus. In this case, the server will force everyone to use CELT instead. If you are the administrator of the server and would like to force people to use Opus, please refer to https://wiki.mumble.info/wiki/FAQ/English#How_do_I_force_usage_of_the_Opus_codec_.28opusthreshold.29.3F.

**Comment by peylight** [comment]
The server is using murmur 1.3.3
Some client using Humla Client (Android) 1.2.5 (Mumla 3.5.6)
Should i kick them to fix problem?

**Comment by TerryGeng** [comment]
Please refer to https://wiki.mumble.info/wiki/FAQ/English#How_do_I_force_usage_of_the_Opus_codec_.28opusthreshold.29.3F
