### ISSUE TITLE
NoneType object has no attribute strip in cmd_shortlist

### ISSUE THREAD

**Issue by mweinelt** [azlux/botamusique#278]
**Describe the bug**

```pytb
[2021-05-16 20:13:18,475] > [Thread-2882] > [.mumbleBot.py-wrapped:264] bot: received command "sl" with arguments "None" from deraffe
[2021-05-16 20:13:18,482] > [Thread-2882] > [.mumbleBot.py-wrapped:326] bot: command sl failed with error: 
Traceback (most recent call last):
  File "/nix/store/ffba4h0231668yvwnpvvl7pip3kvwha9-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 322, in message_received
    self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, argument)
  File "/nix/store/ffba4h0231668yvwnpvvl7pip3kvwha9-botamusique-unstable-2021-05-16/share/botamusique/command.py", line 1092, in cmd_shortlist
    if parameter.strip() == "*":
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Affected version**
https://github.com/azlux/botamusique/commit/1c283654fda42cd9ea00716f2b8cfe9bada77a5e

**To Reproduce**
1, `!sl`
2. `sl: Command failed with error: AttributeError: 'NoneType' object has no attribute 'strip'`

**Expected behavior**
Again, catching Exceptions :wink: 

**Additional context**
```
[20:13:07] To musique.lossy.network: !search stellaris
[20:13:08] (Private) musique.lossy.network: Found:
1 - [URL] To The End Of The Galaxy (From Stellaris Original Game Soundtrack) (recent added)
2 - [URL] To The End Of The Galaxy (From Stellaris Original Game Soundtrack) (Additional Take) (recent added)
3 - [URL] The Celestial City (From Stellaris Original Game Soundtrack) (recent added)
4 - [URL] The Birth Of a Star (From Stellaris Original Game Soundtrack) (recent added)
5 - [URL] Stellaris | Creation and Beyond - Full Orchestra Session and Music Video (recent added)
6 - [URL] Spatial Lullaby (From Stellaris Original Game Soundtrack) (recent added)
7 - [URL] Sigmatauri (From Stellaris Original Game Soundtrack) (recent added)
8 - [URL] Riding The Solar Wind (From Stellaris Original Game Soundtrack) (recent added)
9 - [URL] Pillars of Creation (From Stellaris Original Game Soundtrack) (recent added)
10 - [URL] Luminescence (From Stellaris Original Game Soundtrack) (recent added)
11 - [URL] Journey Beyond the Galaxy (From Stellaris Original Game Soundtrack) (recent added)
12 - [URL] In Search Of Life (From Stellaris Original Game Soundtrack) (recent added)
13 - [URL] Infinite Being (From Stellaris Original Game Soundtrack) (recent added)
14 - [URL] Infinite Being (From Stellaris Original Game Soundtrack) (Additional Take) (recent added)
15 - [URL] Gravitational Constant (From Stellaris Original Game Soundtrack) (recent added)
16 - [URL] Genesis (From Stellaris Original Game Soundtrack) (recent added)
17 - [URL] Faster Than Light (From Stellaris Original Game Soundtrack) (Instrumental) (recent added)
18 - [URL] Faster Than Light (From Stellaris Original Game Soundtrack) (recent added)
19 - [URL] Distant Nebula (From Stellaris Original Game Soundtrack) (Instrumental) (recent added)
20 - [URL] Distant Nebula (From Stellaris Original Game Soundtrack) (recent added)
21 - [URL] Deep Space Travels (From Stellaris Original Game Soundtrack) (recent added)
22 - [URL] Battle For Supremacy (From Stellaris Original Game Soundtrack) (recent added)
23 - [URL] Alpha Centauri (From Stellaris Original Game Soundtrack) (recent added)
Use !sl {indexes} to play the item you want.

[20:13:18] To musique.lossy.network: !sl
[20:13:18] (Private) musique.lossy.network: sl: Command failed with error: AttributeError: 'NoneType' object has no attribute 'strip'.
```

**Comment by mweinelt** [comment]
Sorry, this is because of a local patch I applied. Incomplete version of #273.
