### ISSUE TITLE
Decoding audio message leads to crashing

### ISSUE THREAD

**Issue by TheNamelessWonderer** [azlux/botamusique#304]
**Describe the bug**
When the bot is in the channel it seems to randomly crash.

**Affected version**
The exact version you're using (git commit id). You should **always** only report bugs which you can reproduce on the latest version (`uif` branch), however **always** state the current commit id here (in case there are new commits between your report and us looking at it)
Latest docker and testing docker

**To Reproduce**
1. Join channel
2. Wait for bot to crash
3. See error

**Expected behavior**
The bot shouldn't crash.

**Additional context**
The error is:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 134, in run
    self.loop()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 219, in loop
    self.read_control_messages()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 293, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 299, in dispatch_control_message
    self.sound_received(message)
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 499, in sound_received
    pos += size.decode(message[pos:pos + 10])
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/tools.py", line 98, in decode
    self.value = - result
TypeError: bad operand type for unary -: 'NoneType
```
I'm not sure if this has anything to do with positional audio.

**Comment by azlux** [comment]
Hi, it's an issue with [pymumble](https://github.com/azlux/pymumble/) not botamusique.
Look like an issue with the VarInt decoding because the server send you a bad formated value.
Can you check the mumble server (murmur) version you use ? and the options you use (positionnal, whispering, audio, stereo...) ?

**Comment by TheNamelessWonderer** [comment]
Hello I’m using the latest version of murmur 1.4.0 branch compiled from GitHub in a docker container. I also have positional audio setup and in use in minecraft using the minecraft mumble link fabric mod. The bot is using stereo. Hopefully that’s everything you need.

**Comment by TerryGeng** [comment]
I can't see the cause of this crash. The bot should be able to handle positional audio, I have tested that. The format of the audio message didn't change in 1.4.x. I have also extensively tested murmur 1.4.0 with the bot.

I'm very confused. What is wrong in this case? 🤔

**Comment by TerryGeng** [comment]
A quick remedy here: stop using the `when_nobody_in_channel` option. Comment that line in your config file. I will stop the bot from receiving audio messages.

I know it is not the ultimate fix, but just in case you want to keep using the bot before we find out the cause.

**Comment by TheNamelessWonderer** [comment]
Sorry miss click! That line is commented out for me already.

**Comment by TerryGeng** [comment]
One more thing: for the sake of debugging, can you replace these lines from `/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/tools.py`
https://github.com/azlux/pymumble/blob/790a5262b0f454d3a66a2c58ac69ac5327dfc279/pymumble_py3/tools.py#L97-L100

into
```
        if is_negative:
            try:
                self.value = - result
            except TypeError as e:
                print(varint.hex())
                raise e
        else:
            self.value = result
```

**Comment by TheNamelessWonderer** [comment]
Well I changed it and it crashed again:
```
[2022-01-03 10:53:39,439] > [UpdateThread] > [util.py:129] update: no new version found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 134, in run
    self.loop()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 219, in loop
    self.read_control_messages()
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 293, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 299, in dispatch_control_message
    self.sound_received(message)
  File "/botamusique/venv/lib/python3.10/site-packages/pymumble_py3/mumble.py", line 487, in sound_received
    pos += session.decode(message[pos:pos + 10])
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```
This time positional audio wasn't in use when it crashed I joined from another PC when the same user was connected on another PC.

**Comment by TerryGeng** [comment]
Any updates on this issue?

**Comment by TheNamelessWonderer** [comment]
So far this seems to have stopped. I'll comment back if it happens again! Thank you
