### ISSUE TITLE
Pyradios 1.0.0 and 1.0.1 throws a socket.herror

### ISSUE THREAD

**Issue by emankced** [azlux/botamusique#306]
**Describe the bug**
After updating pyradios from 0.0.22 to 1.0.1 my botamusique instance was not able start because a socket.herror exception is being thrown. I was able to reproduce this issue on Fedora and Raspberry Pi OS by using the default settings with just changing the host settings.
Downgrading pyradios back to 0.0.22 resolved this issue for me.

**Affected version**
botamusique version: Commit c624c327c3e50a36cfff47f362d6aa836325a887
pyradios version: 1.0.0 and 1.0.1

**To Reproduce**
1. Clone the botamusique repo.
2. Creating a virtualenv and pull all requirements using pip.
3. Copy the configuration.default.ini to configuration.ini and change the host setting to your server's address.
4. Try to start botamusique: `python mumbleBot.py --config configuration.ini`.
5. Botamusique crashes.

**Expected behavior**
Botamusique should start normally as it does with pyradios-0.0.22.

**Logs**
Exception message on my Fedora system:
```
Network failure
Traceback (most recent call last):
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 0] Resolver Error 0 (no error)
Traceback (most recent call last):
  File "/tmp/botamusique/mumbleBot.py", line 25, in <module>
    import command
  File "/tmp/botamusique/command.py", line 14, in <module>
    from pyradios import RadioBrowser
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/__init__.py", line 3, in <module>
    from pyradios.radios import RadioBrowser
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/radios.py", line 29, in <module>
    class RadioBrowser:
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/radios.py", line 60, in RadioBrowser
    base_url = pick_base_url()
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/tmp/botamusique/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 0] Resolver Error 0 (no error)
```

Exception message on my Raspberry Pi:
```
Network failure
Traceback (most recent call last):
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/botamusique/botamusique/mumbleBot.py", line 25, in <module>
    import command
  File "/home/botamusique/botamusique/command.py", line 14, in <module>
    from pyradios import RadioBrowser
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/__init__.py", line 3, in <module>
    from pyradios.radios import RadioBrowser
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/radios.py", line 29, in <module>
    class RadioBrowser:
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/radios.py", line 60, in RadioBrowser
    base_url = pick_base_url()
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/home/botamusique/.local/lib/python3.9/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 2] Host name lookup failure
```

**Desktop:**
 - OS: Fedora Workstation
 - Version: 35
 - DNS resolver: systemd-resolved
---
 - OS: Raspberry Pi OS
 - Version: 11 (bullseye)
 - DNS resolver: dnsmasq

**Additional context**
Pyradios checks if the socket.herror is a "Unknown Host" error: https://github.com/andreztz/pyradios/blob/3565993cdfd305ceb9cb0c40df01cf78547f8ecb/pyradios/base_url.py#L57
On my machines the errors were "Resolver Error 0 (no error)" and "Host name lookup failure" so I assume we should look into which exceptions and error messages pyradios is supposed to catch leading us to a conclusion which exceptions botamusique might have to catch and eventually reporting back to the pyradios project in case they did intend to catch those exceptions.

**Comment by TerryGeng** [comment]
I would suggest you report this issue to pyradio. Of course we can make a workaround, but I think it is the responsibility of pyradio team to fix their own bug.

**Comment by azlux** [comment]
Did you system resolve `all.api.radio-browser.info` ?
(end reverse of all ip return by the first resolve ?

**Comment by emankced** [comment]
I reported the issue to the pyradios repo. Thanks @azlux for the reverse DNS tip. You were right that one IP didn't resolve correctly.

**Comment by emankced** [comment]
The problem was patched in pyradios and now botamusique works again, so I close this issue as well.

**Comment by TerryGeng** [comment]
Thanks for letting us know!
