### ISSUE TITLE
Short freeze and several errors when requesting playlist with it being disabled

### ISSUE THREAD

**Issue by Gert-dev** [azlux/botamusique#315]
**Describe the bug**
When `!playlist` is executed immediately after starting the bot (and `save_playlist` is `False`), the bot consumes a lot of CPU resources for a while and then barfs out a large amount of errors (see below).

**Affected version**
v7.2.2

**To Reproduce**
1. Start the bot.
2. Join the Mumble server yourself.
3. Send command `!playlist` to the bot.
4. Observe the CPU usage of the bot spiking for a while, and it then sending a large amount of errors in the system journal.

**Expected behavior**
The bot does not fail, but reports the playlist is either disabled or empty.

**Server (please complete the following information):**
 - OS: Arch Linux ARMv7
 - Browser [e.g. chrome, safari]: n.a.
 - Version [e.g. 22]: kernel 5.16.1

**Desktop (please complete the following information):**
N.a.

**Smartphone (please complete the following information):**
N.a.

**Additional context**
The following errors are printed immediately after a couple of seconds of the bot seemingly freezing (on my relatively slow server system):

```
Jan 24 19:00:32 botamusique: [Jan 24 19:00:32 INFO] bot: received command "playlist" with arguments "" from MumbleUser
Jan 24 19:00:32 botamusique: [Jan 24 19:00:32 INFO] bot: received command "playlist" with arguments "" from MumbleUser
Jan 24 19:00:49 botamusique: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: [Jan 24 19:00:49 ERROR] ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
Jan 24 19:00:49 botamusique:     ie_result = self._real_extract(url)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2667, in _real_extract
Jan 24 19:00:49 botamusique:     raise ExtractorError(
Jan 24 19:00:49 botamusique: yt_dlp.utils.ExtractorError: '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
Jan 24 19:00:49 botamusique:     return func(self, *args, **kwargs)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
Jan 24 19:00:49 botamusique:     ie_result = ie.extract(url)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 638, in extract
Jan 24 19:00:49 botamusique:     raise type(e)(e.msg, **kwargs)
Jan 24 19:00:49 botamusique: yt_dlp.utils.ExtractorError: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/botamusique/media/url_from_playlist.py", line 31, in get_playlist_info
Jan 24 19:00:49 botamusique:     info = ydl.extract_info(url, download=False)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1358, in extract_info
Jan 24 19:00:49 botamusique:     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1385, in wrapper
Jan 24 19:00:49 botamusique:     self.report_error(str(e), e.format_traceback())
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 923, in report_error
Jan 24 19:00:49 botamusique:     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 864, in trouble
Jan 24 19:00:49 botamusique:     raise DownloadError(message, exc_info)
Jan 24 19:00:49 botamusique: yt_dlp.utils.DownloadError: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: [Jan 24 19:00:49 ERROR] ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
Jan 24 19:00:49 botamusique:     ie_result = self._real_extract(url)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2667, in _real_extract
Jan 24 19:00:49 botamusique:     raise ExtractorError(
Jan 24 19:00:49 botamusique: yt_dlp.utils.ExtractorError: '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
Jan 24 19:00:49 botamusique:     return func(self, *args, **kwargs)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
Jan 24 19:00:49 botamusique:     ie_result = ie.extract(url)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 638, in extract
Jan 24 19:00:49 botamusique:     raise type(e)(e.msg, **kwargs)
Jan 24 19:00:49 botamusique: yt_dlp.utils.ExtractorError: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:49 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:49 botamusique: Traceback (most recent call last):
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/botamusique/media/url_from_playlist.py", line 31, in get_playlist_info
Jan 24 19:00:49 botamusique:     info = ydl.extract_info(url, download=False)
Jan 24 19:00:49 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1358, in extract_info
Jan 24 19:00:50 botamusique:     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1385, in wrapper
Jan 24 19:00:50 botamusique:     self.report_error(str(e), e.format_traceback())
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 923, in report_error
Jan 24 19:00:50 botamusique:     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 864, in trouble
Jan 24 19:00:50 botamusique:     raise DownloadError(message, exc_info)
Jan 24 19:00:50 botamusique: yt_dlp.utils.DownloadError: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: [Jan 24 19:00:50 ERROR] ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
Jan 24 19:00:50 botamusique:     ie_result = self._real_extract(url)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2667, in _real_extract
Jan 24 19:00:50 botamusique:     raise ExtractorError(
Jan 24 19:00:50 botamusique: yt_dlp.utils.ExtractorError: '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
Jan 24 19:00:50 botamusique:     return func(self, *args, **kwargs)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
Jan 24 19:00:50 botamusique:     ie_result = ie.extract(url)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 638, in extract
Jan 24 19:00:50 botamusique:     raise type(e)(e.msg, **kwargs)
Jan 24 19:00:50 botamusique: yt_dlp.utils.ExtractorError: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/media/url_from_playlist.py", line 31, in get_playlist_info
Jan 24 19:00:50 botamusique:     info = ydl.extract_info(url, download=False)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1358, in extract_info
Jan 24 19:00:50 botamusique:     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1385, in wrapper
Jan 24 19:00:50 botamusique:     self.report_error(str(e), e.format_traceback())
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 923, in report_error
Jan 24 19:00:50 botamusique:     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 864, in trouble
Jan 24 19:00:50 botamusique:     raise DownloadError(message, exc_info)
Jan 24 19:00:50 botamusique: yt_dlp.utils.DownloadError: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: [Jan 24 19:00:50 ERROR] ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
Jan 24 19:00:50 botamusique:     ie_result = self._real_extract(url)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2667, in _real_extract
Jan 24 19:00:50 botamusique:     raise ExtractorError(
Jan 24 19:00:50 botamusique: yt_dlp.utils.ExtractorError: '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
Jan 24 19:00:50 botamusique:     return func(self, *args, **kwargs)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
Jan 24 19:00:50 botamusique:     ie_result = ie.extract(url)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 638, in extract
Jan 24 19:00:50 botamusique:     raise type(e)(e.msg, **kwargs)
Jan 24 19:00:50 botamusique: yt_dlp.utils.ExtractorError: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: During handling of the above exception, another exception occurred:
Jan 24 19:00:50 botamusique: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/media/url_from_playlist.py", line 31, in get_playlist_info
Jan 24 19:00:50 botamusique:     info = ydl.extract_info(url, download=False)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1358, in extract_info
Jan 24 19:00:50 botamusique:     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1385, in wrapper
Jan 24 19:00:50 botamusique:     self.report_error(str(e), e.format_traceback())
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 923, in report_error
Jan 24 19:00:50 botamusique:     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 864, in trouble
Jan 24 19:00:50 botamusique:     raise DownloadError(message, exc_info)
Jan 24 19:00:50 botamusique: yt_dlp.utils.DownloadError: ERROR: [generic] '' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:" ) to search YouTube
Jan 24 19:00:50 botamusique: [Jan 24 19:00:50 ERROR] bot: command playlist failed with error: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/mumbleBot.py", line 328, in message_received
Jan 24 19:00:50 botamusique:     self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, argument)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/command.py", line 420, in cmd_play_playlist
Jan 24 19:00:50 botamusique:     if len(items) > 0:
Jan 24 19:00:50 botamusique: TypeError: object of type 'NoneType' has no len()
Jan 24 19:00:50 botamusique: [Jan 24 19:00:50 ERROR] bot: command playlist failed with error: Traceback (most recent call last):
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/mumbleBot.py", line 328, in message_received
Jan 24 19:00:50 botamusique:     self.cmd_handle[command_exc]['handle'](self, user, text, command_exc, argument)
Jan 24 19:00:50 botamusique:   File "/opt/botamusique/botamusique/command.py", line 420, in cmd_play_playlist
Jan 24 19:00:50 botamusique:     if len(items) > 0:
Jan 24 19:00:50 botamusique: TypeError: object of type 'NoneType' has no len()
```

In Mumble, the bot posts:

```
botamusique: playlist: Command failed with error: TypeError: object of type 'NoneType' has no len().
```

**Comment by hamilton5** [comment]
!playlist <youtube link> is for adding a youtube playlist, seems they don't check if it's null or empty first and its going haywire.. if you want to see your current list use !q aka !queue

https://github.com/azlux/botamusique/wiki/Command-Help-and-Examples

**Comment by Gert-dev** [comment]
Oops, it is indeed meant for YouTube playlists. I knew about the `!queue` command as well, but was incorrectly trying `!playlist` before, which is when I stumbled upon this issue. Thanks for the tip, though.

**Comment by TerryGeng** [comment]
> !playlist is for adding a youtube playlist, seems they don't check if it's null or empty first and its going haywire.. if you want to see your current list use !q aka !queue

You are completely right. I know... these two concepts are confusing, especially when coding. It took me some thinking to name these things separately in the code base :)

But anyway, you remind me to check users' input. Will do shortly.

**Comment by TerryGeng** [comment]
Fixed in https://github.com/azlux/botamusique/commit/e9bb9d3489b75f8e8f233a2317ba5d261471b1f7
