### ISSUE TITLE
Some commands don't work, bot is crash

### ISSUE THREAD

**Issue by thejustsoul** [azlux/botamusique#34]
**Describe the bug**
Bot show error and crash (random), some commands don't work

Example:
`!help` (is not crash)
```
2019-01-13 17:04:24: Starting in DEBUG loglevel
2019-01-13 17:04:28: help -  by USER
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "mumbleBot.py", line 203, in message_received
    self.send_msg(var.config.get('strings', 'help'), text)
  File "mumbleBot.py", line 521, in send_msg
    own_channel.send_text_message(msg)
  File "/home/bot/mumble-tools/botamusique/pymumble/pymumble_py3/channels.py", line 175, in send_text_message
    raise TextTooLongError(self.mumble_object.get_max_message_length())
pymumble.pymumble_py3.errors.TextTooLongError: Maximum allowed length: 0
```

`!url https://www.youtube.com/watch?v=nGVqz4fm_FA` (is crash)
```
2019-01-13 17:43:09: Starting in DEBUG loglevel
2019-01-13 17:43:11: url - <a href="https://www.youtube.com/watch?v=nGVqz4fm_FA">https://www.youtube.com/watch?v=nGVqz4fm_FA</a> by USER
[{'type': 'url', 'user': 'USER', 'ready': 'validation', 'url': 'https://www.youtube.com/watch?v=nGVqz4fm_FA'}]
[youtube] nGVqz4fm_FA: Downloading webpage
[youtube] nGVqz4fm_FA: Downloading video info webpage
[youtube] Downloading just video nGVqz4fm_FA because of --no-playlist
2019-01-13 17:43:14: Async download next asked
2019-01-13 17:43:14: launch_music asked{'type': 'url', 'url': 'https://www.youtube.com/watch?v=nGVqz4fm_FA', 'ready': 'no', 'title': 'Hippie Sabotage - Devil Eyes', 'user': 'USER', 'duration': 2.2333333333333334}
2019-01-13 17:43:14: Current music wasn't ready, Downloading...
2019-01-13 17:43:14: Download index:0
2019-01-13 17:43:14: {'type': 'url', 'url': 'https://www.youtube.com/watch?v=nGVqz4fm_FA', 'ready': 'downloading', 'title': 'Hippie Sabotage - Devil Eyes', 'user': 'USER', 'duration': 2.2333333333333334}
Traceback (most recent call last):
  File "mumbleBot.py", line 563, in <module>
    botamusique = MumbleBot(args)
  File "mumbleBot.py", line 97, in __init__
    self.loop()
  File "mumbleBot.py", line 498, in loop
    self.launch_music()
  File "mumbleBot.py", line 351, in launch_music
    self.download_music(index=0)
  File "mumbleBot.py", line 440, in download_music
    self.send_msg(var.config.get('strings', "download_in_progress") % var.playlist[index]['title'])
  File "mumbleBot.py", line 521, in send_msg
    own_channel.send_text_message(msg)
  File "/home/bot/mumble-tools/botamusique/pymumble/pymumble_py3/channels.py", line 175, in send_text_message
    raise TextTooLongError(self.mumble_object.get_max_message_length())
pymumble.pymumble_py3.errors.TextTooLongError: Maximum allowed length: 0
```

Chat is clear, help text not show
Command is work: `!radio`, `!file`, `!stop`, `!kill`, `!joinme`
Not work: `!help`, `!list`, `!queue`, `!v`

**Affected version**
Latest version

**To Reproduce**
1. Send to chat !help command
2. See error

**Additional context**
Debian GNU/Linux `8.11 (jessie) x86`
Mumble server version is `1.2.19`
Mumble client version is `1.2.19` and latest `1.3.0`

Manual install (bot not work without it): 
from `aptitude` - `libjpeg-dev`
from `venv/bin/pip` - `six werkzeug jinja2 click itsdangerous` 

```
$ venv/bin/pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): opuslib==2.0.0 in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.4.0 in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): flask in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): youtube-dl in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): python-magic in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): mutagen in ./venv/lib/python3.4/site-packages (from -r requirements.txt (line 7))
Cleaning up...
```

w/o configuration.ini the same behavior

**Comment by azlux** [comment]
Hi @thejustsoul 

Look like the server set the bot max message limit at 0. `TextTooLongError: Maximum allowed length: 0`
Can you give me your server URL ? You can send me a mail if you don't want it public.

If not, you can enable the pymumble debug log (into the config file) and give me the output of the first 5 second. [you can paste the output here](https://azlux.fr/bin/)

You can also check the file `/etc/mumble-server.ini` , have you override the textmessagelength ?

Az

**Comment by azlux** [comment]
Some news.
Thanks @Lartza for pointing me the good information.
Some people use the limit 0 to precise "no message limit".
It's a pymumble error. https://github.com/azlux/pymumble/issues/29
I will keep you inform as soon I've fixed it.

**Comment by thejustsoul** [comment]
In mumble config `textmessagelength=0`

**Comment by thejustsoul** [comment]
UPD: If in mumble conifg set `timeout=5`, bot drop from server, if `10` not drop (like would).

**Comment by azlux** [comment]
I don't remember seeing timeout configuration on Mumble server.
Do you have more information ?

**Comment by thejustsoul** [comment]
```
Murmur and Mumble are usually pretty good about cleaning up hung clients, but occasionally one will get stuck on the server. The timeout setting will cause a periodic check of all clients who haven't communicated with the server in this many seconds - causing zombie clients to be disconnected.
Note that this has no effect on idle clients or people who AFK. It will only affect people who are already disconnected, and just haven't told the server.

default:
timeout=30
```
`https://wiki.mumble.info/wiki/Murmur.ini#timeout`

I have `5`s and bot lost connection, i change to `10`s and bot not disconnect, normal work.

**Comment by azlux** [comment]
Can we close this issue now ?
