### ISSUE TITLE
I have encountered some problems

### ISSUE THREAD

**Issue by rabook** [azlux/botamusique#383]
2024-03-13 23:55:00.020693+08:00/botamusique/mumbleBot.py:10: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
2024-03-13 23:55:00.020775+08:00import audioop
2024-03-13 23:55:01.268292+08:00[Mar 13 23:55:01 INFO] library: rebuild directory cache
2024-03-13 23:55:01.268391+08:00[Mar 13 23:55:01 INFO] library: rebuild directory cache
2024-03-13 23:55:01.269371+08:00[Mar 13 23:55:01 INFO] bot: botamusique version unknown, starting...
2024-03-13 23:55:01.269429+08:00[Mar 13 23:55:01 INFO] bot: botamusique version unknown, starting...
2024-03-13 23:55:01.272920+08:00Exception in thread Thread-1:
2024-03-13 23:55:01.272966+08:00Traceback (most recent call last):
2024-03-13 23:55:01.272984+08:00File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-03-13 23:55:01.273773+08:00self.run()
2024-03-13 23:55:01.273845+08:00File "/botamusique/venv/lib/python3.11/site-packages/pymumble_py3/mumble.py", line 125, in run
2024-03-13 23:55:01.274118+08:00if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occurred, exit here
2024-03-13 23:55:01.274174+08:00^^^^^^^^^^^^^^
2024-03-13 23:55:01.274195+08:00File "/botamusique/venv/lib/python3.11/site-packages/pymumble_py3/mumble.py", line 160, in connect
2024-03-13 23:55:01.274400+08:00self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLS)
2024-03-13 23:55:01.274548+08:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-13 23:55:01.274580+08:00File "/usr/local/lib/python3.11/ssl.py", line 1476, in wrap_socket
2024-03-13 23:55:01.275706+08:00context.load_cert_chain(certfile, keyfile)
2024-03-13 23:55:01.275762+08:00FileNotFoundError: [Errno 2] No such file or directory

**Comment by luca0N** [comment]
Are you specifying an authentication certificate in the configuration file, as shown in the snippet below? If so, make sure the path exists.

https://github.com/azlux/botamusique/blob/97d47d70739af7728a35abfa72dd988e9e15998e/configuration.example.ini#L18

Also, what version of botamusique are you using? Are you running a stable release or are you running it based on the latest commit in the master branch?

**Comment by rabook** [comment]
I'm using Docker for deployment. I tried specifying the certificate location but it didn't start successfully.
![Uploading 屏幕截图 2024-03-14 183350.png…]()

**Comment by luca0N** [comment]
Hey, sorry for the delay.

I was able to reproduce this with the `BAM_CERTIFICATE` environment variable. `pymumble` looks for the Mumble authentication certificate file based on the filesystem from inside the container (i.e., if you have a certificate in the host, you can't just pass its canonical path to the container).

The solution was to create a mount bind and put the certificate in there, like so:

```sh
# Directory to share with the container filesystem
CONTAINER_MOUNT_PATH="/home/luca0n/botamusique_container"

# Create the container shared directory (if it doesn't exist)
mkdir -p "$CONTAINER_MOUNT_PATH"

# Move the (existing) certificate file to the shared directory
mv myCertificate.pem "$CONTAINER_MOUNT_PATH"

# Create a new botamusique container with the shared directory,
# and then pass the certificate pass from the container filesystem
docker run \
    --mount "type=bind,src=/home/luca0n/botamusique_container,destination=/botamusique" \
    -e "BAM_CERTIFICATE=/botamusique/myCertificate.pem" ...
```

Hope this has been helpful!

**Comment by rabook** [comment]
谢谢你 我远方的朋友
