### ISSUE TITLE
fails to start with "Invalid version" error

### ISSUE THREAD

**Issue by madddi** [azlux/botamusique#384]
**Describe the bug**
Bot fails 

**Affected version**
Docker Hub image, `latest` and `testing`

**To Reproduce**
* Create `docker-compose.yml` as described in Wiki
* Start the container

**Expected behavior**
Container should start.

**Screenshots**
```
musicbot  | /botamusique/mumbleBot.py:10: DeprecationWarning: 'audioop' is deprecated and slated for removal in Python 3.13
musicbot  |   import audioop
musicbot  | [Apr 23 07:09:54 INFO] library: rebuild directory cache
musicbot  | [Apr 23 07:09:54 INFO] library: rebuild directory cache
musicbot  | [Apr 23 07:09:54 INFO] bot: botamusique version unknown, starting...
musicbot  | [Apr 23 07:09:54 INFO] bot: botamusique version unknown, starting...
musicbot  | [Apr 23 07:09:54 INFO] bot: load playlist from previous session
musicbot  | [Apr 23 07:09:54 INFO] bot: load playlist from previous session
musicbot  | Exception in thread UpdateThread:
musicbot  | Traceback (most recent call last):
musicbot  |   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
musicbot  |     self.run()
musicbot  |   File "/usr/local/lib/python3.11/threading.py", line 975, in run
musicbot  |     self._target(*self._args, **self._kwargs)
musicbot  |   File "/botamusique/mumbleBot.py", line 189, in check_update
musicbot  |     new_version, changelog = util.check_update(self.get_version())
musicbot  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
musicbot  |   File "/botamusique/util.py", line 122, in check_update
musicbot  |     if version.parse(new_version) > version.parse(current_version):
musicbot  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
musicbot  |   File "/botamusique/venv/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
musicbot  |     return Version(version)
musicbot  |            ^^^^^^^^^^^^^^^^
musicbot  |   File "/botamusique/venv/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
musicbot  |     raise InvalidVersion(f"Invalid version: '{version}'")
musicbot  | packaging.version.InvalidVersion: Invalid version: 'unknown'
```

**Desktop (please complete the following information):**
Linux / Docker

**Additional context**
Thanks for your work!

**Comment by Gunzinger** [comment]
You might be able to work around this by disabling the auto update check in your `configuration.ini`.
Reference: https://github.com/azlux/botamusique/blob/master/configuration.example.ini#L85

**Comment by madddi** [comment]
@Gunzinger Thanks, that helped!

**Comment by Gunzinger** [comment]
Happy to hear that,
schönes Wochenende :)
