### ISSUE TITLE
Crashes when choosing an nonexistent radio channel

### ISSUE THREAD

**Issue by bamtan** [azlux/botamusique#41]
**Describe the bug**
When selecting a radio channel `!radio <channelname>` that doesn't exist, the bot crashes completely. 

**Affected version**
 89b11d8

**To Reproduce**
`!radio <nonexistent_name>` 

**Expected behavior**
Should output error e.g. "No radio titled X available"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 9 

**Additional context**
Log:
```
2019-02-16 18:24:41: radio - sdaasd by bamtan
2019-02-16 18:24:41: Async download next asked
Traceback (most recent call last):
  File "mumbleBot.py", line 620, in <module>
    args = parser.parse_args()
  File "mumbleBot.py", line 100, in __init__
    self.mumble = pymumble.Mumble(host, user=self.username, port=port, password=password, tokens=tokens,
  File "mumbleBot.py", line 555, in loop
    self.mumble.sound_output.add_sound(audioop.mul(raw_music, 2, self.volume))
  File "mumbleBot.py", line 439, in launch_music

  File "/home/bam/botamusique/media/radio.py", line 11, in get_radio_server_description
    res = re.search(p, url)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by azlux** [comment]
No really, if the bot don't find the name, it will use it as a url.
I will check that. Srry for the delay.
