### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by DejarW** [azlux/botamusique#46]
Python 3.6.8
OS Freebsd 11.2

when tryimg to play playlist from youtube or soundcloud, I get an error:
example playlist: https://soundcloud.com/melanus-anus/sets/audiomatic

[download] Finished downloading playlist: audiomatic
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "mumbleBot.py", line 261, in message_received
    if media.playlist.get_playlist_info(url=self.get_url_from_input(parameter), start_index=offset, user=user):
  File "/usr/home/jan/botamusique/media/playlist.py", line 16, in get_playlist_info
    'title': info['entries'][j]['title'],
KeyError: 'title'

**Comment by azlux** [comment]
Ji.
Can you post the youtube-dl version ?

**Comment by DejarW** [comment]
youtube-dl   2019.4.7

**Comment by azlux** [comment]
ok, found the issue, soundcloud don't give any title with the youtube-dl requests.
Should work with youtube playlist by the way.

**Comment by azlux** [comment]
Is that better ?
