### ISSUE TITLE
Play direct url to mp3 is crash a bot

### ISSUE THREAD

**Issue by thejustsoul** [azlux/botamusique#5]
**Describe the bug**
If you pass a direct link to mp3 to the bot, the script will fail.

**To Reproduce**
1. Say bot `!url http://url.tld/123.mp3`
2. See error

**Expected behavior**
Play file from direct url

**Additional context**
Error log:
```
2018-06-04 23:06:48: play_url - <a href="http://192.168.1.123/123.mp3">http://192.168.1.123/123.mp3</a> by user
[generic] 123: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 123: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[download] Destination: /tmp/5cee745417c743389475785eec49c911.mp3
[download] 100% of 402.18KiB in 00:00
[ffmpeg] Post-process file /tmp/5cee745417c743389475785eec49c911.mp3 exists, skipping
Traceback (most recent call last):
  File "./mumbleBot.py", line 383, in <module>
    botamusique = MumbleBot(args)
  File "./mumbleBot.py", line 87, in __init__
    self.loop()
  File "./mumbleBot.py", line 332, in loop
    self.launch_next()
  File "./mumbleBot.py", line 255, in launch_next
    im = Image.open(var.config.get('bot', 'tmp_folder') + hashlib.md5(url.encode()).hexdigest() + '.jpg')
  File "/home/user/env_botamusique/lib/python3.4/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/5cee745417c743389475785eec49c911.jpg'
```

**Comment by azlux** [comment]
Thank for the report.
The bot is trying to download the thumbnail, so it fail.
If will change that on next release (today if I have time)

**Comment by thejustsoul** [comment]
```
venv/bin/python mumbleBot.py -v
2019-01-13 23:43:48: Starting in DEBUG loglevel
2019-01-13 23:43:55: url - <a href="http://xx.xx.xx.xx:88/1.mp3">http://xx.xx.xx.xx:88/1.mp3</a> by USER
[{'ready': 'validation', 'user': 'USER', 'type': 'url', 'url': 'http://xx.xx.xx.xx:88/1.mp3'}]
[generic] 1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "mumbleBot.py", line 173, in message_received
    if media.url.get_url_info():
  File "/home/bot/mumble-tools/botamusique/media/url.py", line 15, in get_url_info
    var.playlist[index]['duration'] = info['duration'] / 60
KeyError: 'duration'
```

**Comment by azlux** [comment]
Can you check again ? The last commit must solve the issue.

**Comment by thejustsoul** [comment]
Reinstall bot..
```
2019-01-15 01:39:47: url - <a href="http://xx.xx.xx.xx:88/1.mp3">http://xx.xx.xx.xx:88/1.mp3</a> by USER
[{'type': 'url', 'url': 'http://xx.xx.xx.xx:88/1.mp3', 'user': 'Mr.Robot', 'ready': 'validation'}]
[generic] 1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/mumble-tools/botamusique/mumbleBot.py", line 225, in message_received
    if var.playlist[-1]['duration'] > var.config.getint('bot', 'max_track_duration'):
KeyError: 'duration'
```
