### ISSUE TITLE
Silently fails on conversion failure

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#80]
**Describe the bug**
```ERROR: audio conversion failed: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.```

This results in the bot not realizing there is no mp3 generated, and just still trying to play the mp3 file without errors of it not existing. m4a file is left to the tmp folder

**Affected version**
0216103b69f90385940c4f91e5d4b1688f1fa59f

**To Reproduce**
1. Have an ffmpeg with no AAC decoder
2. !url a video with AAC audio
3. See console errors about missing AAC decoder
4. Bot tries to start playing a non-existent file and just stays silent without error

**Expected behavior**
Fail on the ffmpeg error and announce the video download failed

**Comment by Lartza** [comment]
This actually results in the tmp folder containing the m4a AND an empty mp3 file. Installing a new ffmpeg and trying to play the same video results in silence because we still have the empty mp3 and the bot thinks it's already downloaded.

This shouldn't be an issue for future users though if we just make the bot fail earlier on the ffmpeg conversion error.

**Comment by TerryGeng** [comment]
Maybe I can cook up some file size check... Or I can get some clues from the return value of ffmpeg

**Comment by Lartza** [comment]
I'm not sure if you can get the ffmpeg return values unless youtube-dl returns them but one would hope youtube-dl somehow catches them and returns something about errors in the callback

**Comment by TerryGeng** [comment]
I headed into the source of youtube-dl and saw these lines:

https://github.com/ytdl-org/youtube-dl/blob/bee6451fe88dbe8d983150cb17565d1c3e9024f7/youtube_dl/postprocessor/ffmpeg.py#L228-L235

```
        if self._downloader.params.get('verbose', False):
            self._downloader.to_screen('[debug] ffmpeg command line: %s' % shell_quote(cmd))
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
        stdout, stderr = p.communicate()
        if p.returncode != 0:
            stderr = stderr.decode('utf-8', 'replace')
            msg = stderr.strip().split('\n')[-1]
            raise FFmpegPostProcessorError(msg)
```

It seems that youtube-dl will raise an exception if the return code of ffmpeg is not 0.

I think I can manage to catch this error and display in the log of the bot.

**Comment by TerryGeng** [comment]
I didn't test this commit since the proxy is slow again and I can't think of how this part can go wrong :D 
Please help me check it, thanks.

**Comment by Lartza** [comment]
```
ERROR: audio conversion failed: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.
[Feb 28 07:10:14 ERROR MainThread] bot: download failed with error:
 Traceback (most recent call last):
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 265, in run_ffmpeg
    FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 336, in run
    self.run_ffmpeg(path, new_path, acodec, more_opts)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 267, in run_ffmpeg
    raise AudioConversionError(err.msg)
youtube_dl.postprocessor.common.AudioConversionError: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2064, in post_process    files_to_delete, info = pp.run(info)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 339, in run
    'audio conversion failed: ' + e.msg)
youtube_dl.utils.PostProcessingError: audio conversion failed: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mumbleBot.py", line 464, in download_music
    ydl.extract_info(url)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1999, in process_info    self.post_process(filename, info_dict)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2066, in post_process    self.report_error(e.msg)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/lartza/botamusique/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: audio conversion failed: This build of ffmpeg does not include a "aac" decoder needed for input stream #0:0.

[Feb 28 07:10:14 INFO MainThread] bot: removing music from the playlist
```
and we still have an empty mp3 and the original m4a, and if you play it again bot thinks the file exists and announces the playback (even if it never plays anything since it's an empty file)

**Comment by TerryGeng** [comment]
If I said this is the expected behavior what do you think? :-P
I think as long as the bot logs the error and removes the item then we are good.
But I think I need to delete the file. Let me work on it (or if you want to add these lines for me in mumbleBot.py near line 464).
