### ISSUE TITLE
AttributeError: module 'util' has no attribute 'get_recursive_filelist_sorted'

### ISSUE THREAD

**Issue by LDelOff** [azlux/botamusique#84]
**I enter:**
!file
**I get:**
**mumble:**
file: Command failed with error: AttributeError: module 'util' has no attribute 'get_recursive_filelist_sorted'.
**console:**
[Feb 29 08:40:09 INFO Thread-2] bot: received command file -  by L_DelOff
[Feb 29 08:40:09 ERROR Thread-2] bot: command file failed with error: Traceback (most recent call last):
  File "mumbleBot.py", line 276, in message_received
    self.cmd_handle[command](self, user, text, command, parameter)
  File "/root/botamusique/command.py", line 220, in cmd_play_file
    files = util.get_recursive_filelist_sorted(var.music_folder)
AttributeError: module 'util' has no attribute 'get_recursive_filelist_sorted'

Apparently for this reason the web interface does not work:
![image](https://user-images.githubusercontent.com/51275636/75604362-b98a9100-5ae8-11ea-8c78-dc3fce01a3b6.png)

root@orangepi3:~/botamusique# python3 mumbleBot.py
[Feb 29 08:35:44 INFO MainThread] bot: botamusique version 5.1, starting...
[Feb 29 08:35:44 INFO MainThread] Starting web interface on 192.168.10.10:8181
[Feb 29 08:35:44 INFO MainThread] bot: load playlist from previous session
 * Serving Flask app "interface" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://192.168.10.10:8181/ (Press CTRL+C to quit)
[2020-02-29 08:35:53,909] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/botamusique/interface.py", line 91, in decorated
    return f(*args, **kwargs)
  File "/root/botamusique/interface.py", line 99, in index
    files = util.get_recursive_filelist_sorted(var.music_folder)
AttributeError: module 'util' has no attribute 'get_recursive_filelist_sorted'
192.168.10.2 - - [29/Feb/2020 08:35:53] "GET / HTTP/1.1" 500 -

client: mumble 1.3.0(win 10)
server: orange pi 3. Armbian bullseye with Linux 5.5.0-sunxi64
[configuration.txt](https://github.com/azlux/botamusique/files/4270079/configuration.txt)

**Comment by TerryGeng** [comment]
Sorry about the inconvenience. I just fixed it in b71a6a0d4e41054ba66699cef9ba1f7a78eecc85. Please have a look.
