### ISSUE TITLE
Error when adding music or radio

### ISSUE THREAD

**Issue by Klowd8007** [azlux/botamusique#85]
When I add a song from youtube with !url, the bot crashes and I have this error in the logs.
Something similar happens when I try to play a radio url that was working before. It doesn't crash, but I get the error "radio: Command failed with error: TypeError: '_sre.SRE_Match' object is not subscriptable"

**Affected version**
commit 52d98c7257c5507b74438076730d370f2fd69598
version 5.2

Logs:
```
[Feb 29 18:52:34 INFO MainThread] bot: botamusique version 5.1, starting...
[Feb 29 18:52:35 INFO MainThread] bot: load playlist from previous session
[Feb 29 18:52:59 INFO Thread-2] bot: received command url -  <a href="https://www.youtube.com/watch?v=SMS_BXhnZ6k">https://www.youtube.com/watch?v=SMS_BXhnZ6k</a> by 
[Feb 29 18:52:59 INFO Thread-2] bot: file existed for url https://www.youtube.com/watch?v=SMS_BXhnZ6k
[Feb 29 18:52:59 ERROR Thread-2] bot: command url failed with error: Traceback (most recent call last):
  File "/home/pi/botamusique/mumbleBot.py", line 276, in message_received
    self.cmd_handle[command](self, user, text, command, parameter)
  File "/home/pi/botamusique/command.py", line 282, in cmd_play_url
    music = var.playlist.append(music)
  File "/home/pi/botamusique/media/playlist.py", line 32, in append
    item = util.get_music_tag_info(item)
  File "/home/pi/botamusique/util.py", line 85, in get_music_tag_info
    file_no_ext = match[1]
TypeError: '_sre.SRE_Match' object is not subscriptable


[Feb 29 18:53:19 INFO Thread-3] bot: received command url - <a href="https://www.youtube.com/watch?v=zABLecsR5UE">https://www.youtube.com/watch?v=zABLecsR5UE</a> by 
[Feb 29 18:53:25 INFO Thread-3] bot: verifying the duration of url https://www.youtube.com/watch?v=zABLecsR5UE
[Feb 29 18:53:25 INFO Thread-3] cmd: add to playlist: [url] Lewis Capaldi - Someone You Loved (https://www.youtube.com/watch?v=zABLecsR5UE) by 
[Feb 29 18:53:25 INFO MainThread] bot: play music [url] Lewis Capaldi - Someone You Loved (https://www.youtube.com/watch?v=zABLecsR5UE) by 
[Feb 29 18:53:25 INFO MainThread] bot: current music isn't ready, downloading...
[Feb 29 18:53:25 INFO MainThread] bot: downloading url (Lewis Capaldi - Someone You Loved) https://www.youtube.com/watch?v=zABLecsR5UE
[Feb 29 18:53:25 INFO MainThread] bot: download attempts 1 / 2
[Feb 29 18:53:36 INFO Thread-4] bot: received command queue -  by 
[Feb 29 18:54:27 INFO MainThread] bot: finished downloading url (Lewis Capaldi - Someone You Loved) https://www.youtube.com/watch?v=zABLecsR5UE, saved to /tmp/f64e490fcc5517848c7bcd5dd5888fa0.mp3.
[Feb 29 18:55:03 INFO MainThread] bot: botamusique version 5.1, starting...
[Feb 29 18:55:04 INFO MainThread] bot: load playlist from previous session
[Feb 29 18:55:13 INFO Thread-2] bot: received command queue -  by 
[Feb 29 18:55:16 INFO Thread-3] bot: received command stop -  by 
[Feb 29 18:55:16 INFO Thread-3] bot: music stopped.
[Feb 29 19:00:57 INFO Thread-4] bot: received command help -  by 
[Mar 01 11:24:46 INFO Thread-5] bot: received command update -  by 
[Mar 01 11:24:59 INFO Thread-5] update: new version, start updating...
[Mar 01 11:25:24 INFO Thread-5] update: update pip librairies dependancies
[Mar 01 11:30:15 INFO Thread-6] bot: received command radio - energie by 
[Mar 01 11:30:15 ERROR Thread-6] bot: command radio failed with error: Traceback (most recent call last):
  File "/home/pi/botamusique/mumbleBot.py", line 276, in message_received
    self.cmd_handle[command](self, user, text, command, parameter)
  File "/home/pi/botamusique/command.py", line 331, in cmd_play_radio
    var.playlist.append(music)
  File "/home/pi/botamusique/media/playlist.py", line 32, in append
    item = util.get_music_tag_info(item)
  File "/home/pi/botamusique/util.py", line 138, in get_music_tag_info
    music['title'] = match[1]
TypeError: '_sre.SRE_Match' object is not subscriptable


[Mar 01 11:34:22 INFO MainThread] bot: botamusique version 5.2, starting...
[Mar 01 11:34:23 INFO MainThread] bot: load playlist from previous session
[Mar 01 11:36:41 INFO MainThread] bot: botamusique version 5.2, starting...
[Mar 01 11:36:41 INFO MainThread] bot: load playlist from previous session
[Mar 01 11:38:08 INFO Thread-2] bot: received command energie -  by 
[Mar 01 11:38:15 INFO Thread-3] bot: received command radio - energie by 
[Mar 01 11:38:15 ERROR Thread-3] bot: command radio failed with error: Traceback (most recent call last):
  File "/home/pi/botamusique/mumbleBot.py", line 276, in message_received
    self.cmd_handle[command](self, user, text, command, parameter)
  File "/home/pi/botamusique/command.py", line 331, in cmd_play_radio
    var.playlist.append(music)
  File "/home/pi/botamusique/media/playlist.py", line 32, in append
    item = util.get_music_tag_info(item)
  File "/home/pi/botamusique/util.py", line 138, in get_music_tag_info
    music['title'] = match[1]
TypeError: '_sre.SRE_Match' object is not subscriptable_

```

**Comment by Lartza** [comment]
@TerryGeng https://github.com/azlux/botamusique/commit/3e0b5f5cfdcb66efe032713ef01e852cc9b4366d

This only works on 3.6+ and Debian for example still ships 3.4.2 and 3.5.3 in LTS releases.

**Comment by Lartza** [comment]
@azlux What Python versions do you officially want to support? 3.5 gets security fixes from the Python foundation until September but Debian supports their Stretch 3.5 until 2022 :S

**Comment by azlux** [comment]
My own opinion is 3.6 because of f-string I use a lot. I will migrate current code from str.format() to f-string. It's make code cleaner.
But currently, only this regex is affected by 3.5

**Comment by Klowd8007** [comment]
Should I update to python 3.6+? If so, should I run this `python3 -m venv venv` after I've installed it?

**Comment by azlux** [comment]
@Klowd8007 should be `python3 -m venv --upgrade venv`

**Comment by Lartza** [comment]
@Klowd8007 Updating to Buster (I am assuming you are on Raspbian) would probably be preferable to just manually updating python3 fwiw. Raspbian doesn't support older releases as long as Debian does but I'm not sure if they've dropped support for everything older than Buster yet.

**Comment by Klowd8007** [comment]
@Lartza Yes I am. I'm still on jessie. 
I've been able to install python 3.6 and now it's working
