### ISSUE TITLE
Automode

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#93]
If you don't have music into your music folder, the autoplay mode fail.
```
Mar 09 18:51:57 lyoko python[27294]: 37.18.163.7 - - [09/Mar/2020 18:51:57] "POST /xana/post HTTP/1.1" 200 -
Mar 09 18:51:59 lyoko python[27294]: Traceback (most recent call last):
Mar 09 18:51:59 lyoko python[27294]:   File "/root/botamusique/mumbleBot.py", line 671, in <module>
Mar 09 18:51:59 lyoko python[27294]:     var.bot.loop()
Mar 09 18:51:59 lyoko python[27294]:   File "/root/botamusique/mumbleBot.py", line 397, in loop
Mar 09 18:51:59 lyoko python[27294]:     if var.playlist.next():
Mar 09 18:51:59 lyoko python[27294]:   File "/root/botamusique/media/playlist.py", line 473, in next
Mar 09 18:51:59 lyoko python[27294]:     self.refresh()
Mar 09 18:51:59 lyoko python[27294]:   File "/root/botamusique/media/playlist.py", line 459, in refresh
Mar 09 18:51:59 lyoko python[27294]:     _list = [get_item_wrapper_from_dict(var.bot, _dict, "AutoPlay") for _dict in dicts]
Mar 09 18:51:59 lyoko python[27294]: TypeError: 'NoneType' object is not iterable
Mar 09 18:51:59 lyoko systemd[1]: bot1.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 18:51:59 lyoko systemd[1]: bot1.service: Failed with result 'exit-code'.
```

**Comment by azlux** [comment]
Are you sure this commit didn't add new bug ?
I'm not able to start the bot anymore.
```
Mar 10 19:34:34 lyoko python[30670]: [Mar 10 19:34:34 INFO MainThread] library: rebuild directory cache
Mar 10 19:34:34 lyoko python[30670]: [Mar 10 19:34:34 INFO MainThread] bot: load playlist from previous session
Mar 10 19:34:37 lyoko python[30657]: [2020-03-10 19:34:37,610] ERROR in app: Exception on / [GET]
Mar 10 19:34:37 lyoko python[30657]: Traceback (most recent call last):
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
Mar 10 19:34:37 lyoko python[30657]:     response = self.full_dispatch_request()
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
Mar 10 19:34:37 lyoko python[30657]:     rv = self.handle_user_exception(e)
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
Mar 10 19:34:37 lyoko python[30657]:     reraise(exc_type, exc_value, tb)
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Mar 10 19:34:37 lyoko python[30657]:     raise value
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
Mar 10 19:34:37 lyoko python[30657]:     rv = self.dispatch_request()
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
Mar 10 19:34:37 lyoko python[30657]:     return self.view_functions[rule.endpoint](**req.view_args)
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/interface.py", line 90, in decorated
Mar 10 19:34:37 lyoko python[30657]:     return f(*args, **kwargs)
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/interface.py", line 141, in index
Mar 10 19:34:37 lyoko python[30657]:     path_tags_lookup = build_path_tags_lookup()
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/interface.py", line 121, in build_path_tags_lookup
Mar 10 19:34:37 lyoko python[30657]:     id_tags_lookup = var.music_db.query_tags_by_ids(list(var.cache.file_id_lookup.values()))
Mar 10 19:34:37 lyoko python[30657]:   File "/root/botamusique/database.py", line 266, in query_tags_by_ids
Mar 10 19:34:37 lyoko python[30657]:     "WHERE %s" % condition_str, ids).fetchall()
Mar 10 19:34:37 lyoko python[30657]: sqlite3.OperationalError: incomplete input
Mar 10 19:34:37 lyoko python[30657]: 37.18.163.7 - - [10/Mar/2020 19:34:37] "GET /xana/ HTTP/1.1" 500 -
```
